// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDui6PGhD_Tuxho0OmEXYkhjgotVX8HXNw',
    appId: '1:203183729640:web:15625ed393b5f93364d25d',
    messagingSenderId: '203183729640',
    projectId: 'soundfile-f8afa',
    authDomain: 'soundfile-f8afa.firebaseapp.com',
    databaseURL: 'https://soundfile-f8afa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soundfile-f8afa.firebasestorage.app',
    measurementId: 'G-SEBZ26X688',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANX3HkGmlY1kTaGASj6Hpk5Qm-MxpE1sE',
    appId: '1:203183729640:android:045eb60c10993c1a64d25d',
    messagingSenderId: '203183729640',
    projectId: 'soundfile-f8afa',
    databaseURL: 'https://soundfile-f8afa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soundfile-f8afa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqWxf03nUlF7ZUsBOlbAqhRHxp-0VY3mc',
    appId: '1:203183729640:ios:bdaf79124bd2674d64d25d',
    messagingSenderId: '203183729640',
    projectId: 'soundfile-f8afa',
    databaseURL: 'https://soundfile-f8afa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soundfile-f8afa.firebasestorage.app',
    iosBundleId: 'com.example.soundcanvasflutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqWxf03nUlF7ZUsBOlbAqhRHxp-0VY3mc',
    appId: '1:203183729640:ios:bdaf79124bd2674d64d25d',
    messagingSenderId: '203183729640',
    projectId: 'soundfile-f8afa',
    databaseURL: 'https://soundfile-f8afa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soundfile-f8afa.firebasestorage.app',
    iosBundleId: 'com.example.soundcanvasflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDui6PGhD_Tuxho0OmEXYkhjgotVX8HXNw',
    appId: '1:203183729640:web:e11c865bd488d3a964d25d',
    messagingSenderId: '203183729640',
    projectId: 'soundfile-f8afa',
    authDomain: 'soundfile-f8afa.firebaseapp.com',
    databaseURL: 'https://soundfile-f8afa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soundfile-f8afa.firebasestorage.app',
    measurementId: 'G-FR1M7XSH4P',
  );
}
